### ISSUE TITLE
The select_line property of the Code component highlights two lines even if only one line is filled in

### ISSUE THREAD

**Issue by Malian** [surface-ui/surface_site#14]
I am using FF86. The issue does not happen with Chrome.

```elixir
<#Code
  language="elixir"
  module={{ SurfaceSiteWeb.GettingStarted.RenderlessComponent.Example }}
  line_range={{ 2..38 }}
  show_line_numbers
  selected_lines={{ [15] }}
/>
``` 
![image](https://user-images.githubusercontent.com/553321/111869195-71057600-897e-11eb-916f-450f12179dd2.png)

**Comment by Malian** [comment]
From the slack channel:

> To be complete in my explanations, with the current implementation a single line is represented as "15-16" and this is not correct regarding the doc from https://prismjs.com/plugins/line-highlight/. It should be "15". I refactored the code in order to have a single number when there is a single line to be compliant with the doc. It works en FF but not on chrome, the line is not highlighted. My conclusion is that, the bug is only with chrome. But as I said, it works on the website with Chrome and FF

**Comment by msaraiva** [comment]
Fixed in https://github.com/surface-ui/surface_site/commit/dd11f736bbb7cad564a41362075f8b9dc933962b.
