### ISSUE TITLE
Fresh install of SurfaceSite raises a compile Error

### ISSUE THREAD

**Issue by Malian** [surface-ui/surface_site#22]
Steps to reproduce:

1. Checkout to master
2. Remove the `_build` and `deps` folders
3. Get and compile the dependencies: `mix deps.get` and `mix deps.compile`
4. Run the server: `iex -S mix phx.server`

```log
[I] ➜ iex -S mix phx.server
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Compiling 79 files (.ex)

== Compilation error in file lib/surface_site_web/live/slots.ex ==
** (SyntaxError) nofile:292: unexpected token: ":" (column 25, code point U+003A)
    (surface 0.3.2) expanding macro: Surface.sigil_H/2
    lib/surface_site_web/live/slots.ex:10: SurfaceSiteWeb.Slots.render/1
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

__Remarks__: The error does not occur if you checkout on the previous commit: 0db6877afba3c25a68f25cf07480822246e21ae1 so I suppose we introduced regression when simplyfing the `Code` component in the last commit: 6004d9dbadd69849b4b9d14d5d8a2157fcd3f241. It's really strange that the CI didn't catch it. (Edit: Ah, there is not CI ^^)

**Comment by msaraiva** [comment]
@Malian yeah. That's all my fault. I'm reverting this change until we find a better way as discussed [here](https://github.com/surface-ui/surface_markdown/pull/1#issuecomment-811328934). 😢

**Comment by msaraiva** [comment]
Done. Let me know if you still find any issue. Thanks!
