### ISSUE TITLE
Add https

### ISSUE THREAD

**Issue by NULLx76** [surface-ui/surface_site#3]
It would be nice if the demo site (<http://surface-demo.msaraiva.io/getting_started>) was available under https.

Especially as Firefox recently added a https only mode, which shows the following warning on the demo site.
![image](https://user-images.githubusercontent.com/1809198/106940835-535bb480-6722-11eb-89dd-f8765a936bd5.png)

I understand that this doesn't need to have the top priority, but nowadays setting up https is easy and free, using something like [let's encrypt](https://letsencrypt.org/).

**Comment by msaraiva** [comment]
Hi @NULLx76!

The plan is to have all that set up when we move to `surface-ui.org`.

**Comment by msaraiva** [comment]
https://surface-ui.org is now available.
