### ISSUE TITLE
The form examples should use an atom name for name

### ISSUE THREAD

**Issue by joshuataylor** [surface-ui/surface_site#36]
For example:
https://surface-ui.org/builtincomponents/Field

It should show the atom type instead, especially for a changeset.

**Comment by Malian** [comment]
Hi @joshuataylor !

I am not sure what you would like to change? Could you please elaborate?

Phoenix accepts both atom and string, so Surface should to. See https://github.com/surface-ui/surface/issues/321 and https://github.com/surface-ui/surface/pull/319 for more explanation.

@miguel-s create a PR on Phoenix Ecto: https://github.com/phoenixframework/phoenix_ecto/pull/139 to give proper error message to the user when they use changeset. 

If you have to pass an atom you should be explicit:
```
<Field name={{ :name }}>
```
I am closing this for now. If you believe the examples should be improved, feel free to open a PR, help on documentation are very appreciated!

**Comment by joshuataylor** [comment]
Yep, that was the exact issue I had, I'm glad it's solved.

I was going to contribute doc fixes but completely forgot, I'll have a read through and add notes I found during my implementation. :+1:
