### ISSUE TITLE
Missing docs for serving Surface components

### ISSUE THREAD

**Issue by andrhua** [surface-ui/surface_site#37]
I apologize for such nitpicking, but I couldn't find in docs how to actually serve components from router (specifically that it should be `Surface.LiveView`). I guess it's obvious for those who had already bought in complexity of LiveView, but still it would be not that burdensome to mention it, say, under Components Basic section :)

**Comment by Malian** [comment]
Hi @affficionado ! 

Thanks for reporting this. I transferred the issue to the `surface_site` repository as it is related to the website documentation.

Serving a Surface live view is as simple as:
```elixir
live "/", DashboardLive, :index # Where DashboardLive is a `Surface.LiveView`
```
It is exactly the same as what you would do with PhoenixLiveView.

The idea of the documentation is to point out the difference between Surface and LiveView, not to rewrite the Phoenix Live View documentation. That being said, we already received that kind of feedback, and so I believe we should improve the documentation.

Help are really appreciated, do you feel comfortable to propose a PR that could help future Surface newcomers?
