### ISSUE TITLE
Surface version not updated in latest "Getting Started" page?

### ISSUE THREAD

**Issue by ktnyt** [surface-ui/surface_site#62]
Hi all, this might just be me but accessing the [Getting Started](https://surface-ui.org/getting_started) shows Surface version 0.6.0 in the "Installation" section. It seems that the version has been bumped a while ago but is not being properly updated (maybe due to deployment or some other issue). It would be nice if the page can show version 0.7.X since 0.6.X isn't compatible with LiveView 0.17.X.

**Comment by msaraiva** [comment]
Site updated!
